#!/usr/bin/env bash
#configures a new Ubuntu machine.

sudo apt update
sudo apt install -y nginx
sudo chown -R ubuntu /var/www
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo service nginx start
