#!/usr/bin/env bash
#configures a new Ubuntu machine.

sudo apt-get -y update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo service nginx start
