#!/usr/bin/env bash
# bash

function kill_1() {
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	exit
}

function kill_2() {
	echo "Y U no love me?"
	rm /var/run/myscript.pid
	exit
}

trap kill_2 SIGINT
trap kill_1 SIGTERM
pid=$(pgrep -n)
echo "$pid" > /var/run/myscript.pid
while (true);
do
	echo "To infinity and beyond"
	sleep 2
done
