#!/usr/bin/env bash
# displays the content of the file /etc/passwd.
#username, user id, Home directory path for the user.

while read -r PASSWD;
do
	echo $PASSWD | cut -d ':' -f1,3,6
done < /etc/passwd
