#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes:.

Houre=0
minute=1
while [ "$Houre" -le 12 ];
do
	echo "Hour: $Houre"
	minute=1
	while [ "$minute" -lt 60 ];
	do
		echo "$minute"
		((minute=minute+1))
	done
	((Houre=Houre+1))
done
